INSERT INTO tb_movie_list (name) VALUES ('Terror');
INSERT INTO tb_movie_list (name) VALUES ('Ação');

INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mad Max: Estrada da Fúria', 8.1, 2015, 'Action, Dystopia Sci-fi', 'HBO Max, Prime Video', 'https://m.media-amazon.com/images/M/MV5BZDRkODJhOTgtOTc1OC00NTgzLTk4NjItNDgxZDY4YjlmNDY2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Pulp Fiction: Tempo de Violência', 8.9, 1994, 'Dark Comedy, Drama', 'Prime Video', 'https://m.media-amazon.com/images/M/MV5BM2JiMDdlY2QtNjk2ZC00ZjhhLWE1ZjktMTYyODBmMWZiOGUzXkEyXkFqcGc@._V1_.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Alien: Romulus', 7.1, 2024, 'Monster Horror, Space Sci-fi', 'none', 'https://m.media-amazon.com/images/M/MV5BZmViMjcyYzMtMzdmYi00MjVmLWFhYjQtN2U1ZTU0YWIzNDhlXkEyXkFqcGc@._V1_.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Não! Não Olhe!', 6.8, 2022, 'Alien Invasion, Monster Horror', 'Prime Video', 'https://m.media-amazon.com/images/M/MV5BYTlkMWY5ZGQtNWJiOS00ZWZiLWFmMDMtMjI4YWE4OTk4OTJlXkEyXkFqcGc@._V1_.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_movie (title, score, movie_year, genre, platforms, img_url, short_description, long_description) VALUES ('Matrix', 8.7, 1999, 'Action, Dystopia Sci-fi', 'HBO MAX, Prime Video', 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');

INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (1, 3, 0);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (1, 4, 1);

INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (2, 1, 0);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (2, 2, 1);
INSERT INTO tb_belonging (list_id, movie_id, position) VALUES (2, 5, 2);